services:
  - type: web
    name: smart-summary-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
        sync: false 